name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write # permet au bot de pousser les tags et fichiers
  actions: read # garde l’accès lecture sur les actions
  packages: write # si tu publies des packages GitHub (optionnel)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # indispensable pour Semantic Release

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install python-semantic-release pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release version
